# based on Doki Theme: Hatsune Miku  (Hyper)
background                     #293030
foreground                     #BBBBBB
cursor                         #4DB6AC
selection_background           #313939
color0                         #293030
color1                         #FF16B4
color2                         #80CBC4
color3                         #FFD740
color4                         #64B5F6
color5                         #CE93D8
color6                         #4DB6AC
color7                         #BBBBBB
color8                         #313939
color9                         #FF16B4
color10                        #80CBC4
color11                        #FFD740
color12                        #64B5F6
color13                        #CE93D8
color14                        #4DB6AC
color15                        #FFFFFF
selection_foreground           #BBBBBB

# custom bg
background_image               ~/git/kitty-themes/images/miku-0.02.png
background_image_layout        cscaled

# custom font
font_size                      13.0
font_family                    family="Space Mono"
bold_font                      auto
italic_font                    auto
bold_italic_font               auto
disable_ligatures              always
font_features                  SpaceMono-Regular -liga
font_features                  SpaceMono-Bold -liga
font_features                  SpaceMono-Italic -liga
font_features                  SpaceMono-BoldItalic -liga
